name: quicktube 
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.3.0
  youtube_player_flutter: ^9.1.1
  provider: ^6.0.0
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  firebase_auth_web: ^5.14.1
  cloud_firestore_web: ^4.4.5
  youtube_player_iframe: ^5.2.1
  google_fonts: ^6.0.2
  animate_do: ^4.2.0
  universal_html: ^2.0.8
  flutter_inappwebview: ^6.1.5
  image_picker: ^1.1.2
  icons_plus: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  lottie: ^3.3.1
  flutter_animate: ^4.5.0
  carousel_slider: ^5.0.0
  google_sign_in: ^6.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/images/tech.jpg
    - assets/images/gaming.jpg
    - assets/images/education.jpg
    - assets/images/comedy.jpg
    - assets/images/fitness.jpg
    - assets/lottie/youtube_animation.json
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/foreground.png"
  adaptive_icon_foreground: "assets/foreground.png"
  adaptive_icon_background: "assets/background.png"