// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7_HbQu10MFGM48a9YmXgl39nDgBxrKvw',
    appId: '1:796413342495:web:f239f5430fa8d792daf62a',
    messagingSenderId: '796413342495',
    projectId: 'quicktube-299e2',
    authDomain: 'quicktube-299e2.firebaseapp.com',
    storageBucket: 'quicktube-299e2.firebasestorage.app',
    measurementId: 'G-1Y2338J5Z9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyY_EabaN7HtbxfhFDCqY5Jn9D3hi7K90',
    appId: '1:796413342495:android:96f6c04e8a6a2bd1daf62a',
    messagingSenderId: '796413342495',
    projectId: 'quicktube-299e2',
    storageBucket: 'quicktube-299e2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcIZ55ztS4yU1ylkew-5YrA19yG-SlTc4',
    appId: '1:796413342495:ios:6fe016215e6443fadaf62a',
    messagingSenderId: '796413342495',
    projectId: 'quicktube-299e2',
    storageBucket: 'quicktube-299e2.firebasestorage.app',
    iosClientId: '796413342495-dl8acl44rgjb18jlh52vnruh70ijs5qt.apps.googleusercontent.com',
    iosBundleId: 'com.example.quicktube',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcIZ55ztS4yU1ylkew-5YrA19yG-SlTc4',
    appId: '1:796413342495:ios:6fe016215e6443fadaf62a',
    messagingSenderId: '796413342495',
    projectId: 'quicktube-299e2',
    storageBucket: 'quicktube-299e2.firebasestorage.app',
    iosClientId: '796413342495-dl8acl44rgjb18jlh52vnruh70ijs5qt.apps.googleusercontent.com',
    iosBundleId: 'com.example.quicktube',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7_HbQu10MFGM48a9YmXgl39nDgBxrKvw',
    appId: '1:796413342495:web:555c82466157c1b2daf62a',
    messagingSenderId: '796413342495',
    projectId: 'quicktube-299e2',
    authDomain: 'quicktube-299e2.firebaseapp.com',
    storageBucket: 'quicktube-299e2.firebasestorage.app',
    measurementId: 'G-2D9L26Z24T',
  );

}